Implement flickr tags in Pages. Fixes #3
streeter/pelican-flickrtag pull request #8
Opened 2017-03-20 01:41 UTC by gpoo

The replacement of tags in pages is the same as in articles,
except the name of an attribute. This patch provides a helper
function that deal with both pages and articles.

This proposal is simpler than the one in #3

2017-03-20 01:43 UTC, gpoo commented on pelican_flickrtag/plugin.py
> +    logger.info('[flickrtag]: Found %d photos ids in documents' % total)
Oops. I meant `pages` in the text instead of `documents`, but you get the idea.

2017-04-26 17:40 UTC, streeter requested changes
Can you rebase to fix the merge conflict?

2017-04-26 19:18 UTC, gpoo commented
Done,

2017-04-26 20:24 UTC, streeter approved these changes

2017-04-26 20:24 UTC, merged

2017-04-26 20:26 UTC, streeter commented
Thanks @gpoo! 🎉 I'll get a new release out to PyPI